alter table profile add column if not exists weight_kg numeric;
alter table profile add column if not exists goal text;
create table if not exists activity_plan (
  id bigint generated by default as identity primary key,
  activity_type text,
  days_week numeric,
  minutes_session numeric,
  intensity text,
  met numeric
);
alter table diet_plan add column if not exists confidence text;
alter table meal_log add column if not exists confidence text;
alter table manual_workout add column if not exists activity_type text;
alter table activity_plan disable row level security;
